FROM ailispaw/docker-root-pkg:1.3.5

RUN mkdir -p ${SRC_DIR}/patches && \
    wget -qO ${SRC_DIR}/patches/git-2.7.4.patch https://github.com/buildroot/buildroot/commit/8d73629bb2e4613abd31aa74c686b0a217aca0c6.patch && \
    patch -p1 -d ${BR_ROOT} < ${SRC_DIR}/patches/git-2.7.4.patch
