#!/bin/sh
set -e

source /etc/os-release

BUILDER=ailispaw/docker-root-pkg:${VERSION}

usage() {
  echo "Usage: $(basename $0) <build|install> <package-name> [build options]" >&2
  exit 1
}

build() {
  local TMP_DIR=/tmp/${PKG_NAME}
  local TARGET_DIR=/build/buildroot/output/target

  sudo rm -rf ${TMP_DIR}
  trap "sudo rm -rf ${TMP_DIR}" EXIT
  mkdir -p ${TMP_DIR}
  for i in bin dev/pts etc/ld.so.conf.d etc/network lib sbin usr/bin usr/lib usr/sbin var/lib/misc; do
    sudo mkdir -p ${TMP_DIR}/$i
  done

  docker run --rm -v ${TMP_DIR}:${TARGET_DIR} ${OPTIONS} ${BUILDER} make --quiet ${PACKAGE}

  tar -zc -f ${PKG_FILE} -C ${TMP_DIR} .
}

install() {
  if [ ! -f ${PKG_FILE} ]; then
    build
  fi

  sudo tar -zxv -f ${PKG_FILE} -C /
}

COMMAND=$1
if [ -z "${COMMAND}" ]; then
  usage
fi
shift
PACKAGE=$1
if [ -z "${PACKAGE}" ]; then
  usage
fi
shift
OPTIONS=$*

PKG_NAME=docker-root-pkg-${PACKAGE}
PKG_FILE=${PKG_NAME}.tar.gz

case "${COMMAND}" in
  build)
    build
    ;;
  install)
    install
    ;;
  *)
    usage
esac
